[TAS-4] 로그인 페이지 퍼블리싱
Central-MakeUs/Easybud-Client pull request #17
Opened 2024-01-07 09:00 UTC by ghdtjgus76

## Describe your changes

로그인 페이지 퍼블리싱 진행했습니다.
텍스트의 경우 RN에는 word-break 관련 속성이 없더라고요.
그래서 어쩔 수 없이 split 메소드 사용해서 단어별로 개행해주도록 구현했습니다.

<img width="276" alt="image" src="https://github.com/Central-MakeUs/Easybud-Client/assets/81316050/5057d143-4580-4351-9ee2-3a7564c77ad7">

## To Reviewers

2024-01-07 09:17 UTC, nimod7890 requested changes

2024-01-07 09:17 UTC, nimod7890 commented on src/components/@common/Typography.tsx
이거 빼면 띄어쓰기가 안되나요?

2024-01-07 09:17 UTC, nimod7890 commented on src/screens/OnBoardingFunnelScreen/LoginStepScreen.tsx
> +    <ScreenContainer style={loginStyles.container}>
이거 scroll view 라서 contentContainerStyle 하면 자동으로 적용되긴 하는데 별로일까요

2024-01-07 09:17 UTC, nimod7890 commented on src/components/@common/ScreenContainer.tsx
safe area view에 {...props} 처리 되어있는거 제가 잘못한거같은데 빼면 레이아웃 망가지나요?

2024-01-07 09:18 UTC, ghdtjgus76 commented on src/components/@common/Typography.tsx
이걸 빼면 컨테이너 크기를 넘어가는 글자가 잘립니다..

2024-01-07 09:19 UTC, ghdtjgus76 commented on src/screens/OnBoardingFunnelScreen/LoginStepScreen.tsx
> +    <ScreenContainer style={loginStyles.container}>
음 style 방식이 조금 더 낫긴 할 텐데 싫으시면 변경해도 상관은 없을 거 같아요!

2024-01-07 09:28 UTC, ghdtjgus76 commented on src/components/@common/ScreenContainer.tsx
변경했습니다! 한 번 확인해주세요

2024-01-07 09:30 UTC, nimod7890 commented on src/components/@common/Typography.tsx
세상에 `style={{ flexWrap: 'wrap' }} `속성으로는 적용 안될까요?

2024-01-07 09:31 UTC, ghdtjgus76 commented on src/components/@common/Typography.tsx
다 해봤지만 안 되더라고요

2024-01-07 09:33 UTC, nimod7890 commented on src/screens/OnBoardingFunnelScreen/LoginStepScreen.tsx
> +    <ScreenContainer style={loginStyles.container}>
screencontainer에서 지정하는 style은 scrollView에 들어가는거라 
contentContainerStyle 은 제가 생각해도 직관적이진 않아서 
props는 그대로 두고 props로 들어온 style 이 scroll view 내 contentContainerStyle에만 적용되게 바꿔주시면 좋을 것 같아요

screen container props 에서 'contentContainerStyle', 'style' field omit 처리해주시면 더 좋을 것 같습니다

2024-01-07 09:34 UTC, nimod7890 commented on src/components/@common/ScreenContainer.tsx
아직 푸시가 안된거같아유

2024-01-07 09:34 UTC, nimod7890 commented on src/components/@common/Typography.tsx
속상하군요

2024-01-07 09:39 UTC, ghdtjgus76 commented on src/components/@common/ScreenContainer.tsx
죄송합니다..ㅋㅋ 푸시해서 올려뒀습니다

2024-01-07 09:53 UTC, nimod7890 approved these changes

2024-01-07 09:53 UTC, nimod7890 commented on src/components/@common/ScreenContainer.tsx
> +    <SafeAreaView {...props} style={[styles.safeArea, props.style]}>
악 여기아니라 scrollview에 넣어줘야 해요!!
props도 scrollview props로 유지해주세요ㅜ ㅜ

2024-01-08 04:32 UTC, nimod7890 approved these changes

2024-01-08 04:34 UTC, merged