[TAS-64] TextField multiline 입력되도록 수정
Central-MakeUs/Easybud-Client pull request #19
Opened 2024-01-08 07:35 UTC by ghdtjgus76

## Describe your changes

TextField 컴포넌트에 multiline 속성을 추가했습니다.
추가적으로, value, setValue와 같은 속성은 텍스트 필드 내부에서 상태 값으로 관리하는게 맞을 거 같아서 수정하였습니다.
다만 defaultValue 속성을 추가하여 맨 처음에 텍스트 필드에 보여주고 싶은 값이 있으면 띄워주게 했고 그게 아니라면 placeholder를 보여주도록 했습니다.

![image](https://github.com/Central-MakeUs/Easybud-Client/assets/81316050/e23c591b-904a-421d-875c-cb795a30875f)
![image](https://github.com/Central-MakeUs/Easybud-Client/assets/81316050/8433a408-3826-4739-91bd-1b35ac0bb38f)
![image](https://github.com/Central-MakeUs/Easybud-Client/assets/81316050/068fe534-84c7-451e-baf4-0c108319b9df)

## To Reviewers

2024-01-08 08:06 UTC, nimod7890 requested changes

2024-01-08 08:06 UTC, nimod7890 commented on src/components/@common/TextField/index.tsx
value, setValue를 내부로 옮겨오더라도 컴포넌트 외부에서 입력 중에 validation, clear, Onchange 등등의 과정이 가능해야한다고 생각해서 외부로 빼두었는데요. 내장 Props로 해당 동작을 대체할 수 있다면 저도 좋습니다!
지금 코드에서는 입력 중에 생기는 이벤트를 모두 감지할 수는 없어보이는데 제가 잘 이해한게 맞나요? 아니라면 이 코드대로 괜찮을 것 같습니다.

만약 그렇다면 clear , setText 시 props.onChangeText 사용하는 방향으로 수정하는건 어떨까요?

2024-01-08 08:11 UTC, ghdtjgus76 commented on src/components/@common/TextField/index.tsx
사실 이전 컴포넌트에서 X 아이콘을 눌렀을 때 value 상태 변경이 안 되는 이슈가 있어서 변경하게 되었습니다!
validation이 추가적으로 필요하다면 props로 받아서 사용하는 식으로 사용하는 것이 낫지 않을까요?

혹시 입력 중 생기는 이벤트를 모두 감지할 수는 없다는게 어떤 의미인지 알 수 있을까요?
추가적으로 필요한 onChangeText 같은 이벤트가 필요하다면 customOnChangeTextHandler 같은 걸 props로 받고 해당 함수가 존재한다면 onChangeText 함수에 추가하는 등 기본 이벤트는 컴포넌트 내부에 두되 필요하다면 props로 받는 방식도 좋을 거 같아요!

2024-01-14 19:32 UTC, ghdtjgus76 commented on src/components/@common/TextField/index.tsx
제가 잘못 이해한 것 같아요! 
최종 수정해놨으니까 확인해보시고 말씀 주세요!

2024-01-15 11:43 UTC, nimod7890 approved these changes

2024-01-15 12:03 UTC, merged